name: py36
channels:
- conda-forge
- defaults
dependencies:
- backcall=0.1.0=py_0
- decorator=4.3.0=py_0
- entrypoints=0.2.3=py36_1
- gmp=6.1.2=0
- ipython=6.4.0=py36_0
- ipython_genutils=0.2.0=py36_0
- jedi=0.12.0=py36_0
- jinja2=2.10=py36_0
- jsonschema=2.6.0=py36_1
- libsodium=1.0.16=0
- mistune=0.8.3=py36_1
- pandas=0.22.0=py36_1
- pandoc=2.2.1=0
- pandocfilters=1.4.2=py36_0
- parso=0.2.1=py_0
- pexpect=4.6.0=py36_0
- pickleshare=0.7.4=py36_0
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- python-dateutil=2.7.3=py_0
- pytz=2018.4=py_0
- pyzmq=17.0.0=py36_4
- send2trash=1.5.0=py_0
- simplegeneric=0.8.1=py36_0
- six=1.11.0=py36_1
- terminado=0.8.1=py36_0
- testpath=0.3.1=py36_0
- tornado=5.0.2=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- zeromq=4.2.5=1
- backports=1.0=py36_0
- backports.weakref=1.0rc1=py36_0
- bleach=1.5.0=py36_0
- certifi=2016.2.28=py36_0
- cudatoolkit=8.0=3
- cudnn=6.0.21=cuda8.0_0
- cycler=0.10.0=py36_0
- dbus=1.10.20=0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- h5py=2.7.0=np113py36_0
- hdf5=1.8.17=2
- html5lib=0.9999999=py36_0
- icu=54.1=0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libgpuarray=0.6.9=0
- libiconv=1.14=0
- libpng=1.6.30=1
- libprotobuf=3.4.0=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- mako=1.0.6=py36_0
- markdown=2.6.9=py36_0
- markupsafe=1.0=py36_0
- matplotlib=2.0.2=np113py36_0
- mkl=2017.0.3=0
- mkl-service=1.1.2=py36_3
- nose=1.3.7=py36_1
- numpy=1.13.1=py36_0
- openssl=1.0.2l=0
- patsy=0.4.1=py36_0
- pcre=8.39=1
- pip=9.0.1=py36_1
- protobuf=3.4.0=py36_0
- pygpu=0.6.9=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.2=0
- pyyaml=3.12=py36_0
- qt=5.6.2=5
- readline=6.2=2
- scikit-learn=0.19.0=np113py36_0
- scipy=0.19.1=np113py36_0
- seaborn=0.8=py36_0
- setuptools=36.4.0=py36_1
- sip=4.18=py36_0
- sqlite=3.13.0=0
- statsmodels=0.8.0=np113py36_0
- theano=0.9.0=py36_0
- tk=8.5.18=0
- tqdm=4.15.0=py36_0
- werkzeug=0.12.2=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- yaml=0.1.6=0
- zlib=1.2.11=0
- pip:
  - absl-py==0.2.2
  - astor==0.6.2
  - enum34==1.1.6
  - gast==0.2.0
  - grpcio==1.12.1
  - ipykernel==4.8.2
  - ipython-genutils==0.2.0
  - ipywidgets==7.2.1
  - jupyter==1.0.0
  - jupyter-client==5.2.3
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - jupyterlab==0.32.1
  - jupyterlab-launcher==0.10.5
  - keras==2.2.0
  - keras-applications==1.0.2
  - keras-preprocessing==1.0.1
  - mxnet==0.10.1
  - nbconvert==5.3.1
  - nbformat==4.4.0
  - notebook==5.5.0
  - prompt-toolkit==1.0.15
  - qtconsole==4.3.1
  - tensorboard==1.8.0
  - tensorflow-gpu==1.4.0
  - tensorflow-tensorboard==0.4.0
  - termcolor==1.1.0
  - ujson==1.35
  - webencodings==0.5.1
  - widgetsnbextension==3.2.1
  
